README.md

I also added a note on a boot2docker caveat, as `kitchen-docker` fails to work with boot2docker unless `use_sudo` is set to false.
https://github.com/portertech/kitchen-docker/issues/54#issuecomment-52012749

Added configuration details for use_sudo

---

lib/kitchen/driver/docker.rb

.kitchen.yml example:
```
driver:
name: docker
use_sudo: false
add_host:
myfakehost1.local: 127.0.0.1
myfakehost2.local: 127.0.0.2
```

Fix deprecated -dns argument. Add host support

---

lib/kitchen/driver/docker.rb

This is the minimal effort required in order to make kitchen-docker work on Windows.
Now that docker client 1.6.0 is officially supported on windows it would be super awesome to have kitchen-docker work on windows, too.

Use NUL instead of /dev/null to make it work on Windows

---

README.md

This line is split in two with + concatenation in docker.rb, obviously missed.

Fix docs for run_command default

---

README.md
lib/kitchen/driver/docker.rb

This PR adds support for the "--devices" argument, in order to share raw device files with the guest.
My intended purpose is to be able to use VirtualBox inside a test-kitchen environment, and that mostly works.

Add support for --devices argument to docker.

---

lib/kitchen/driver/docker.rb

Adding build context support for docker. creates Dockerfiles's as temp files, instead of sending to docker CLI using stdin. this allows the use of commands like ADD and COPY. See PR https://github.com/portertech/kitchen-docker/pull/133 for discussion.

Docker - Build Context Support

---

lib/kitchen/driver/docker.rb

Also disables it by default for remote docker because of how slow it is.

Allow disabling the build context.

---

lib/kitchen/driver/docker.rb

This helps avoid busting the layer cache and keeps kitchen runs a
little faster.

Move writing the SSH key to the end of the dockerfile.

---

lib/kitchen/driver/docker.rb

public_key is not an issue when the key is automatically generated, but it is with user supplied input.
ssh-keygen and a lot of text editors automatically append a newline at the end of the public key string. This breaks the Dockerfile RUN instruction which is essentially generated as:
```
RUN echo 'ssh-rsa key-content
' >> /home/kitchen/.ssh/authorized_keys
```
This is not valid. This small patch tackles this issue.

Strip the public_key whitespace

---

lib/kitchen/driver/docker.rb

I was having similar problems to issue #109 where I'm using kitchen-docker to do acceptance testing for puppet modules on centos 7 with systemd. EG after running a puppet module, run serverspec or bats to ensure the module actually installed, configured, and started the service correctly. 
With this patch and the below config, you can get systemd running on the centos7 docker container.
```
driver:
name: docker
privileged: true
provision_command: 
- /usr/bin/systemctl enable sshd
run_command: /usr/sbin/init
```
https://developerblog.redhat.com/2014/05/05/running-systemd-within-docker-container/ and https://hub.docker.com/_/centos/ have a bunch of other things you might have to do regarding /sys/fs/cgroup and deleting some systemd "wants" files but I've found I don't have to do that. …

set "ENV container docker" for CentOS and friends

---

lib/kitchen/driver/docker.rb

Hi,
When the docker container is to be removed, there is a basic timeout of 10s, adding the flag added allow to destroy the container immediately. It allows to gain those 10s between tests.

Don't wait while stopping a container

---

lib/kitchen/driver/docker.rb

Sure, lots of other things use it, so _probably_ it's been required, but apparently, if you use the test-kitchen rake tasks, you can get here without it having been required.
Also, it's just good hygiene.

Require Tempfile

---

README.md
lib/kitchen/driver/docker.rb

@portertech @coderanger for review
This allows mounting tmpfs inside of a docker container, using docker's "--tmpfs" flag.
My use case is that I want to be able to mount tmpfs without needed to run in privileged mode.
In particular, tmpfs is useful with the overlayfs driver where unix domain sockets won't work on overlayfs at all. This workaround allows you to make the usual suspects for unix domain sockets to be tmpfs.

Support tmpfs mounts without requiring privileged mode

---

lib/kitchen/driver/docker.rb

When running /sbin/init from systemd in debian:stretch (recent, unable
to determine since when), it is necessary to include the enviroment
variable container=docker in the Dockerfiles. This is essentially the
same as for recent CentOSes as previously fixed in #192.
Tests with ubuntu-14.04 have shown no hurts and I strongly suspect the
same for other debian-based images.
modified:   lib/kitchen/driver/docker.rb

env container=docker for debians, ext #192

---

lib/kitchen/driver/docker.rb

`emerge sync` is obsolete and already removed as valid sync method.
`emerge --sync` has to be used and is implemented in docker.rb now.

Fix Gentoo support

---

lib/kitchen/driver/docker.rb

This change resolves an error using kitchen-docker where Docker refuses to acknowledge that a build context of `.` includes the Dockerfile when the Dockerfile is given with an absolute path. Here's an example of the error output:
```
$ kitchen converge app-worker-trusty
-----> Starting Kitchen (v1.14.2)
-----> Creating <app-worker-trusty>...
unable to prepare context: The Dockerfile (/Users/andre.arko/chef/Dockerfile-kitchen20161209-24579-1pvw8h7) must be within the build context (.)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of docker -H unix:///var/run/docker.sock build -f …
```

Use relative paths when passing -f Dockerfile

---

lib/kitchen/driver/docker.rb

`/etc/ssh/ssh_host_*` keys are needed for SSH server to work properly, that's why you generate them.
However if user has pre-baked Docker images with already configured SSH server or where keys already exist, - he'll get the following error log: 
```sh
Generating public/private rsa key pair.
/etc/ssh/ssh_host_rsa_key already exists.
Overwrite (y/n)? The command '/bin/sh -c ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''' returned a non-zero code: 1
```
With this change we don't generate SSH keys if they already exist.
----
It's possible to specify custom [`Dockerfile`](https://github.com/test-kitchen/kitchen-docker/blob/master/test/Dockerfile), but I think this PR brings safer defaults for everyone.

Fix ssh_host key generation failure if file already exists

---

README.md

Docker for Windows needs different settings of socket.

Docker for Windows socket example

---

lib/kitchen/driver/docker.rb

Pacman does not resolve .so files, so if an so bump happens with one of these packages, it could break other packages.
`pacman: error while loading shared libraries: libpsl.so.5: cannot open shared object file: No such file or directory` is an example of the error right now.
https://gist.github.com/vodik/5660494

archlinux must be updated when repos are refreshed

---

lib/kitchen/driver/docker.rb

On ubuntu 18.04 continer, /run/sshd directory is used.
You can see below error when you don't create directory.
Missing privilege separation directory: /run/sshd
So I add mkdir

mkdir /run/sshd in container to support ubuntu 18.04

---

lib/kitchen/driver/docker.rb

This commit fixes bug #314.
Check image presence is required because docker command fails if image for remove doesn't exist.

Fix bug #314 - check if image exists before remove.

---

lib/kitchen/driver/docker.rb

This fixes `uninitialized constant Kitchen::Driver::Docker::Base64`.

require base64

---

README.md
lib/kitchen/driver/docker.rb

As I don't have write access in the base branch of the PR #283, I forked from `master`, made the changes of the origin PR and also the one suggested in the comments.
Co-authored-by: @AaronKalair

feat: added use_internal_docker_network feature

---

lib/kitchen/driver/docker.rb

All currently supported (and a bunch of EOL) Fedora distros have dnf and not yum. We should use that to setup the container.
Signed-off-by: Tim Smith <tsmith@chef.io>

On Fedora install the dependencies with dnf not yum

---

.kitchen.yml
README.md
lib/kitchen/driver/docker.rb

The previous opensuse images are deprecated on dockerhub.
Signed-off-by: Tim Smith <tsmith@chef.io>

Add support for the opensuse/leap images

---

.kitchen.yml
lib/kitchen/docker/helpers/container_helper.rb
lib/kitchen/transport/docker.rb

Currently, only one platform name can be used for Windows as the platform name has to be exactly named "windows" as shown in the kitchen config below:
```
platforms:
- name: windows
driver_config:
image: mcr.microsoft.com/windows/servercore:1607
platform: windows
```
This update checks to see if the platform name includes the string "windows" instead (shown in the configuration below):
```
platforms:
- name: windows-chef-12
provisioner:
product_name: chef
product_version: 12.14.89
driver_config:
image: mcr.microsoft.com/windows/servercore:1607
platform: windows
- name: windows-chef-14
provisioner:
product_name: chef
product_version: 14.7.17
driver_config:
image: mcr.microsoft.com/windows/servercore:1607
platform: windows
- name: windows-chef-latest
provisioner:
product_name: chef …
```

Allow Multiple Platform Names for Windows

---

kitchen-docker.gemspec

No need to contrain to the 2.x releases
Signed-off-by: Tim Smith <tsmith@chef.io>

Allow train 3.x dev dep

---

lib/kitchen/docker/container.rb
lib/kitchen/docker/container/linux.rb
lib/kitchen/docker/container/windows.rb
lib/kitchen/docker/helpers/container_helper.rb
lib/kitchen/docker/helpers/image_helper.rb
lib/kitchen/driver/docker.rb
lib/kitchen/transport/docker.rb

require_relative is faster as it requires fewer directory traversals
Signed-off-by: Tim Smith <tsmith@chef.io>

Use require_relative instead of require

---

lib/kitchen/docker/container.rb
lib/kitchen/docker/container/linux.rb
lib/kitchen/docker/container/windows.rb

Signed-off-by: Jeffrey Coe <jeffrey.coe@cerner.com>
Retrieves hostname state data after the container is launched. This fixes an issue where the container ID was not set when it attempted to retrieve the container IP address if the use_internal_docker_network option was set.
Fixes issue #366

Retrieve hostname state data after container is launched

---

lib/kitchen/docker/helpers/cli_helper.rb

Since 19.03, NVIDIA GPUs are now natively supported as devices in the Docker runtime. See https://docs.docker.com/config/containers/resource_constraints/#gpu and https://github.com/NVIDIA/nvidia-docker
For example:
```bash
docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
```
The only change I made in this PR was adding
```ruby
cmd << " --gpus #{config[:gpus]}" if config[:gpus]
```
in `cli_helper.rb`. I tested it locally and it worked. But i'm not sure how to test this without a GPU VM though.
Thanks

Support GPU in docker

---

lib/kitchen/docker/container/linux.rb

The openssh in the latest suse image (opensuse/leap:15) needs all types of ssh keys
Signed-off-by: Michael Geiger <info@mgeiger.de>

suse platform: use system script for ssh key initialization

---

lib/kitchen/docker/helpers/dockerfile_helper.rb

Creating a docker image on Gentoo uses verbose and slow approach to syncing the repository and installing openssh & sudo. This becomes an issue when provisioning Gentoo containers. This pull request:
- replaces the current `emerge --sync` with `emerge-webrsync`, which runs much quicker (21s compared to 2m18s on a test machine);
- emerges openssh and sudo with `--quiet` to decrease verbosity and  `--noreplace` to avoid reinstalling a package that is already installed.
None.

Use less verbose and quicker setup on Gentoo

---

lib/kitchen/driver/docker.rb

Lowercase the instance-name to avoid issues since docker does not allow instance with capital cases
```
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '125'
---- Begin output of docker -H unix:///var/run/docker.sock run -d -p 22 --name standardubuntu2004-vmartinez-VictorsMacBookProloca-gzc7n64i --privileged PyYAML /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes -o UsePrivilegeSeparation=no -o PidFile=/tmp/sshd.pid ----
STDOUT: 
STDERR: docker: invalid reference format: repository name must be lowercase.
See 'docker run …
```

lowercase the instance-name

---

lib/kitchen/docker/helpers/image_helper.rb

Disables docker buildkit (enabled by default on new installs) so that kitchen can get the `docker build` output and parse the image id.
#337

disables docker buildkit (fixes #337)

---

lib/kitchen/docker/helpers/image_helper.rb

Signed-off-by: Collin McNeese <cmcneese@chef.io>
Fixes the error `Could not parse Docker build output for image ID` which was previously mentioned in #337   and #378 
This error is still currently present using the default options with Test Kitchen and `Docker version 20.10.5, build 55c4c88`
Mentions of `Could not parse Docker build output for image ID` located in:
- #337 
- #378

Updates image_helper for additional output line matching

---

README.md
lib/kitchen/docker/helpers/dockerfile_helper.rb

Our org (https://github.com/saltstack-formulas) use `kitchen-docker`
across ~100 repos.  We've already tested this patch successfully with
both:
* https://hub.docker.com/_/almalinux
* https://hub.docker.com/r/rockylinux/rockylinux
N/a.

feat(dockerfile_helper): add support for `almalinux` & `rockylinux`

---

README.md

Line 18 `Please read the Test Kitchen [docs][test_kitchen_docs]...` points to http://kitchen.ci/docs/getting-started/ which doesn't exist.  This changes the link to https://kitchen.ci/docs/getting-started/introduction/
Describe what this change achieves
List any existing issues this PR resolves

README.md: Fix link to getting-started page

---

.kitchen.yml
README.md
lib/kitchen/docker/helpers/cli_helper.rb
lib/kitchen/docker/helpers/image_helper.rb
test/Dockerfile

This PR introduces support for Docker Buildkit and makes it the default way to build containers when executed with a supported version of Docker. Compatibility with the old build system is maintained.
Also introduces the ability to target a specific CPU architecture with docker, allowing builds of cross-platform containers where supported using the `--platform` switch in Docker.
All test suites have been updated to supported OS versions. Cross-platform build tests are also present.
Proper solution for #337

Use Docker BuildKit, support multiple CPU architectures

---

.kitchen.yml
lib/kitchen/docker/helpers/image_helper.rb

#389 described a problem where the output during docker image creation could sometimes include a timestamp. I was unable to find a reference in the docker or buildx source that explains this behavior, and I was also unable to reproduce it, even after installing the same version of Docker that @olhado was using. Nonetheless, I believe it's safe to expand the regex to allow for and ignore this output.
I added an optional, non-capturing group to the image matching regex used when building with Buildkit, which is the default scenario.
The updated regex can be seen and evaluated in [this regex101](https://regex101.com/r/sJldFD/1) sandbox.
Fixes #389

Fix image parser when output includes a duration timestamp

---

.kitchen.yml

- Removed centos-8 due to EOL
- Made debian-9 platform-specific because chef does not support arm64 on 
this OS
Signed-off-by: Andrew Bobulsky <rulerof@gmail.com>
Makes all the tests pass on my M1 machine.
None

Update test suites

---

CHANGELOG.md
lib/kitchen/docker/docker_version.rb

Signed-off-by: Ashique P S <Ashique.saidalavi@progress.com>
Release 2.13.0
The changes include:
- Added CentOSStream and PhotonOS - [@garethgreenaway](https://github.com/garethgreenaway)
- Fixed image parser when output includes a duration timestamp - [@RulerOf](https://github.com/RulerOf)
- Updated the test suites - [@RulerOf](https://github.com/RulerOf)
List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant
Our release process assumes you are using [Conventional Commit messages](https://www.conventionalcommits.org/en/v1.0.0/).
The most important prefixes you should have in mind are:
- `_fix_`: which represents bug fixes, and correlates to a SemVer patch.
- `_feat_`: which represents a new feature, and correlates to a SemVer minor.
- …

Release 2.13.0

---

lib/kitchen/docker/helpers/dockerfile_helper.rb

Make sure the /etc/sudoers.d directory exists before trying to write a file there.
List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant
`_fix_`

 Make sure the /etc/sudoers.d directory exists

---

lib/kitchen/docker/helpers/dockerfile_helper.rb

Breaking almalinux out into it's own platform, Curl is already available in 8 and 9 containers and installing curl on 9 causes a conflict with the already installed curl-minimal package.
- `_fix_`

Breaking almalinux platform out

---

lib/kitchen/docker/helpers/image_helper.rb

When using a custom dockerfile which installs Python modules using pip, the output will sometimes contain the line:
```
Successfully built module_name
```
Since this matches one of the regexes in parse_image_id, it causes the module name to be incorrectly identified as the image ID, which will cause kitchen-docker to fail the "docker run" as it will not have a valid Docker image ID.
This commit processes the "docker build" output in reverse line order, which will ensure that the correct line is matched.

fix: parse_image_id: Process "docker build" output in reverse line order

---

lib/kitchen/docker/helpers/dockerfile_helper.rb

Breaking rockylinux out into it's own platform, Curl is already available in 8 and 9 containers and installing curl on 9 causes a conflict with the already installed curl-minimal package.
- `_fix_`

Breaking rockylinux platform out

---

.github/workflows/ci.yml
.rubocop.yml
kitchen.yml
lib/kitchen/docker/helpers/cli_helper.rb
lib/kitchen/docker/helpers/container_helper.rb
test/integration/capabilities/disabled/capabilities_drop_spec.rb
test/integration/default/disabled/default_spec.rb
test/integration/default/disabled/spec_helper.rb
test/spec/spec_helper.rb

Switch to the buildx builder in GitHub Actions
Our release process assumes you are using [Conventional Commit messages](https://www.conventionalcommits.org/en/v1.0.0/).

Fix: Switch to buildx builder

---

.tailor
Gemfile
Rakefile
kitchen-docker.gemspec
lib/docker/version.rb
lib/kitchen/docker/container.rb
lib/kitchen/docker/container/linux.rb
lib/kitchen/docker/container/windows.rb
lib/kitchen/docker/docker_version.rb
lib/kitchen/docker/erb_context.rb
lib/kitchen/docker/helpers/cli_helper.rb
lib/kitchen/docker/helpers/container_helper.rb
lib/kitchen/docker/helpers/dockerfile_helper.rb
lib/kitchen/docker/helpers/file_helper.rb
lib/kitchen/docker/helpers/image_helper.rb
lib/kitchen/docker/helpers/inspec_helper.rb
lib/kitchen/driver/docker.rb
lib/kitchen/transport/docker.rb
lib/train/docker.rb
test/integration/inspec/inspec_spec.rb
test/spec/docker_spec.rb
test/spec/spec_helper.rb

- Run chefstyle
- Move development dependencies into the Gemfile
- Remove tailor and cane which are no longer maintained
Please describe what this change achieves
List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant
- Major

refactor!: Run chefstlye over the codebase

---

.github/workflows/ci.yml
.github/workflows/publish.yaml
.markdownlint.yaml
Gemfile
README.md
Rakefile
renovate.json
test/spec/spec_helper.rb

- Use reusable workflows
- Use release-please for releasing gem
Signed-off-by: Dan Webb <dan.webb@damacus.io>

feat: Update workflows

---

lib/kitchen/docker/helpers/image_helper.rb

Please describe what this change achieves
List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant
Our release process assumes you are using [Conventional Commit messages](https://www.conventionalcommits.org/en/v1.0.0/).
The most important prefixes you should have in mind are:
- `_fix_`: which represents bug fixes, and correlates to a SemVer patch.
- `_feat_`: which represents a new feature, and correlates to a SemVer minor.
- `_feat!_`:, or `fix!:`, `refactor!:`, etc., which represent a breaking change (indicated by the !) and will result in a major version change.
If you have not included a conventional commit message this can be fixed on merge.

feat: Tell the user when we can't remove the image if it's in use
